### ISSUE TITLE
Support documentation needs to be updated

### ISSUE THREAD

**Issue by mw1688** [awsdocs/aws-support-user-guide#5]
https://docs.aws.amazon.com/awssupport/latest/user/case-management.html

The following wording on the documentation is no longer valid. Support does not exist in top right on the new or old console experience. Please update to avoid confusion for customers. Thank you!

_**To create a support case

    Sign in to the [AWS Management Console](https://console.aws.amazon.com/)

In the upper-right corner, choose Support, and then choose Support Center.**_

**Comment by alextruo** [comment]
Hello, thanks for sending this. This will be fixed soon in documentation.
